const url='https://openrouter.ai/api/v1/chat/completions';
const request=`fetch('${url}')`;
export const cases=[
 ['sdk',`import {OpenRouter as Router} from '@openrouter/sdk';const client=new Router();client.chat.send({messages:[]})`,1,0],
 ['sdk-signal',`import {OpenRouter} from '@openrouter/sdk';const client=new OpenRouter();const c=new AbortController();client.chat.send({}, {fetchOptions:{signal:c.signal}})`,0,0],
 ['other-sdk',`import OpenAI from 'openai';const client=new OpenAI();client.chat.completions.create({})`,0,0],
 ['openai-config',`import OpenAI from 'openai';const cfg={baseURL:'https://openrouter.ai/api/v1'};const client=new OpenAI(cfg);client.chat.completions.create({})`,1,0],
 ['sdk-unrelated',`import {OpenRouter} from '@openrouter/sdk';const client=new OpenRouter();client.chat.send({}, {signal:null});fetch('https://other.org')`,1,0],
 ['direct',request,1,0],
 ['multiline',`fetch(\n'${url}',\n{method:'POST'}\n)`,1,0],
 ['alias',`const u='${url}'; const f=globalThis.fetch; f(u)`,1,0],
 ['template',"const host='openrouter.ai'; const path='/api/v1/chat/completions'; fetch(`https://${host}${path}`)",1,0],
 ['request',`fetch(new Request('${url}'))`,1,0],
 ['request-signal',`const c=new AbortController();const r=new Request('${url}',{signal:c.signal}); fetch(r)`,0,0],
 ['signal-alias',`const c=new AbortController();const s=c.signal;fetch('${url}',{signal:s})`,0,0],
 ['spread-added',`const c=new AbortController();const o={signal:c.signal};fetch('${url}',{...o})`,0,0],
 ['spread-overridden',`const c=new AbortController();const o={signal:c.signal};fetch('${url}',{...o,signal:null})`,1,0],
 ['spread-before-signal',`const c=new AbortController();fetch('${url}',{...external,signal:c.signal})`,0,0],
 ['spread-after-signal',`const c=new AbortController();fetch('${url}',{signal:c.signal,...external})`,0,1],
 ['ordinary',`function fetch(){} fetch('${url}');`,0,0],
 ['shadow',`function f(fetch){fetch('${url}')}`,0,0],
 ['unrelated',`const marker='openrouter';fetch('https://example.org');`,0,0],
 ['computed',`globalThis['fetch']('${url}',{['signal']:null})`,1,0],
 ['two',`${request};\n${request}`,2,0],
 ['unknown-url','fetch(endpoint)',0,1],
 ['unknown-options',`fetch('${url}',options)`,0,1],
 ['reassignment',`let u='${url}';u=external;fetch(u)`,0,1],
 ['conditional',`fetch(flag?'${url}':'https://example.org')`,0,1],
 ['wrapper',`fetch(wrap('${url}'))`,0,1],
 ['unknown-neighbor',`fetch(endpoint);${request}`,1,1],
].map(([name,source,count,unknown])=>({name,source,count,unknown}));
