import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {cases} from './slice-cases.mjs';
import {assessCase} from './assess-case.mjs';
const candidate=fs.realpathSync(process.argv[2]??'.'),output=path.resolve(process.argv[3]);
const selected=cases.filter(c=>!process.argv[4]||c.slice===process.argv[4]);
fs.mkdirSync(output,{recursive:false});const root=path.join(output,'seeds');fs.mkdirSync(root);
for(const c of selected)fs.writeFileSync(path.join(root,`${c.name}.ts`),c.source);
const command=[path.join(candidate,'bin/cli.js'),'run',path.join(candidate,'doctors/convex.mjs'),root,'--format','json'];
const run=spawnSync(process.execPath,command,{encoding:'utf8',maxBuffer:20e6});
fs.writeFileSync(path.join(output,'scan.json'),run.stdout);fs.writeFileSync(path.join(output,'stderr'),run.stderr);
if(run.status!==0)throw Error(run.stderr);
const scan=JSON.parse(run.stdout),group=scan.groups[0];
const rows=selected.map(c=>{
 const file=`${c.name}.ts`,actual=group.checks.filter(k=>k.rule===c.rule).flatMap(k=>k.findings).filter(f=>f.file===file);
 const narrowed=group.semantic.narrowed.filter(n=>n.check===c.rule&&n.files.some(f=>f.file===file));
 return {...c,actual,narrowed,...assessCase(c,actual,narrowed)};
});
const result={command:[process.execPath,...command],exit:run.status,passed:rows.filter(r=>r.passed).length,failed:rows.filter(r=>!r.passed).length,skipped:0,rows};
fs.writeFileSync(path.join(output,'results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({...result,rows:rows.filter(r=>!r.passed).map(r=>({name:r.name,actual:r.actual,coverage:r.narrowed}))}));process.exitCode=result.failed?1:0;
